# Use Node Alpine
FROM node:22-alpine

# Set environment
ENV NODE_ENV=development

# Set working directory
WORKDIR /react-app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY . .

# Expose Vite dev server port
EXPOSE 5173

# Run Vite and bind to all interfaces
CMD npm run dev -- --host